import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import Provider from "./provider";

import {Fredoka} from 'next/font/google';

const fredoka = Fredoka({subsets:['latin']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={fredoka.className}
      ><Provider>
        {children}
        </Provider>
       
      </body>
    </html>
    </ClerkProvider>
  );
}
